[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]
fs_permissions = [{ access = "read-write", path = "../deployments" }]

[fuzz]
runs = 512

[invariant]
runs = 256
depth = 32
fail_on_revert = false

[fmt]
line_length = 120
number_underscore = "thousands"
